name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to Docker Hub'
inputs:
  context:
    description: 'The context path for the Docker build'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  image_name:
    description: 'Name of the image to build and push'
    required: true
  image_tag:
    description: 'Tag for the Docker image'
    default: 'latest'
    required: false
secrets:
  docker_hub_username:
    required: true
  docker_hub_access_token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.docker_hub_username }}
        password: ${{ secrets.docker_hub_access_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ secrets.docker_hub_username }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
